---
title: "R Tipz"
author: "Daniel Casey"
date: "September 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

# Set up

1) load the libraries used by this tutorial
```{r loadpacks, }
#survey analysis
library('survey')
library('srvyr')

#data manipulation
library('dplyr')
library('data.table')

#other
library('ggplot2')

```

2) Prep the various datasets and permutations. Data is coming from the survey package.

```{r loadata}
data(api)

#Prep the datasets
dat_dplyr <- apiclus1
dat_dt <- setDT(copy(apiclus1))
dat_svy <- as_survey_design(apiclus1, dnum, weights = pw, fpc = fpc)


```


# A: Compute Mean,SE, and CI
```{r summarystats}

#dplyr
dat_dplyr %>% summarize(est = mean(api00), se = sd(api00)/sqrt(n())) %>% 
  mutate(lci = est - 1.96 * se, uci = est + 1.96 *se)

#data.table
dat_dt[
         , .(est = mean(api00), se = sd(api00)/sqrt(.N))
       ][ #chain the operations together-- couple all be 1 line
         , .(est, se, lci = (est - 1.96 * se), uci = (est + 1.96 * se))
        ]

#srvyr
dat_svy %>% summarize(est = survey_mean(api00), ci = survey_mean(api00, vartype = 'ci')[2:3]) %>%
  rename(se = est_se ,lci = ci_low, uci = ci_upp)


```

# B: Groups summaries
```{r groupstats}

#dplyr
dat_dplyr %>% group_by(stype) %>% 
  summarize(est = mean(api00), se = sd(api00)/sqrt(n()))

#data.table
dat_dt[, .(est = mean(api00), se = sd(api00)/sqrt(.N)), keyby = 'stype']

#srvyr
dat_svy %>% group_by(stype) %>% summarize(est = survey_mean(api00))


```

# C: Merge datasets
```{r merge}
#create two datasets to merge
m_base <- data.frame(letter = c('A','A','B', 'C'))
m_new <- data.frame(letter = c('A','B', 'D'), num = 1:3)

#basic merge (data.frame or data.table)
merge(m_base, m_new, by = 'letter') #inner join
merge(m_base, m_new, by = 'letter', all.x = T) #left join
merge(m_base, m_new, by = 'letter', all = T)

```


# D: Some ways to recode variables (in data.table)
```{r recodes}

#create a small dataset
rec <- dat_dt[1:5, .(sname, stype, api00)]

#Via Merge into a new variable
school <- data.frame(stype = c('E', 'H', 'M'), stype_name = c('Elem', 'High', 'Middle'))
rec_m <- merge(rec, school, by = 'stype', all.x = T)
rec_m[]

#Overwrite
rec_new <- copy(rec_m)
rec_new[, c('stype', 'stype_name') := .(stype_name, NULL)]
rec_new[]

#subsetting
rec_s = copy(rec)
rec_s[stype == 'E', stype_name := 'Elem']
rec_s[stype == 'H', stype_name := 'High']
rec_s[]
```

# E: Basic flow control
```{r flowontrol}
#if, else if, and else
t <- 1
if(t == 0){
  0
}else if(t == 1){
  1
}else{
  2
}

#For loop
list_to_iterate <- 1:3
for(item in list_to_iterate){
  print(item)
}

#while loop
i = 1
while(i < 4){
  print(i)
  i <- i+1
}


```

# F: Functions
```{r functions}

funky = function() 'get jiggy with it'
funky()

dance = function(x) rep('Dance', x)
dance(1)
dance(5)

```

# G: Scatter 
```{r scatters}

scat = data.frame(x = runif(10), y = rnorm(10))

#Base R
plot(scat$x, scat$y)

#ggplot
ggplot(scat, aes(x = x , y = y)) + geom_point()


```
